const firebase = require("firebase");
// Required for side-effects
require("firebase/firestore");

// Initialize Cloud Firestore through Firebase
firebase.initializeApp({
    apiKey: "AIzaSyC8Bpb-C3RxwueqznJVue9aWA3aGD_wXzM",
    authDomain: "ibuy-mac-1.firebaseapp.com",
    projectId: "ibuy-mac-1"
  });

var db = firebase.firestore();

var retailerPrograms =

[
  {
    "spendRange": "1",
    "retailerRegionCode": "2-109",
    "retailerCode": "2",
    "retailerName": "Food Basics",
    "regionalCode": "K0G",
    "regionCode": "109",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.38%",
    "topCashback": "1.88%",
    "cashback": "1.64%",
    "maxCustomers": "2300",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "8",
    "storeAddressNameAndNumber": "2615 Highway 43",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Kemptville",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "K0G1J0",
    "storeLatitude": "45.018408",
    "storeLongitude": "-75.655345"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "12-106",
    "retailerCode": "12",
    "retailerName": "Loblaws",
    "regionalCode": "K0K",
    "regionCode": "106",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.22%",
    "topCashback": "2.00%",
    "cashback": "1.71%",
    "maxCustomers": "500",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "48",
    "storeAddressNameAndNumber": "1555 Elizabeth Street",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Brighton",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "K0K1H0",
    "storeLatitude": "44.072799",
    "storeLongitude": "-77.737947"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "5-130",
    "retailerCode": "5",
    "retailerName": "Walmart",
    "regionalCode": "K8V",
    "regionCode": "130",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.29%",
    "topCashback": "1.48%",
    "cashback": "1.36%",
    "maxCustomers": "1100",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "64",
    "storeAddressNameAndNumber": "471 2nd Dug Hill Road",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Trenton",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "K8V5T7",
    "storeLatitude": "44.094299",
    "storeLongitude": "-77.605598"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "11-130",
    "retailerCode": "11",
    "retailerName": "Giant Tiger",
    "regionalCode": "K8V",
    "regionCode": "130",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.06%",
    "topCashback": "1.57%",
    "cashback": "1.51%",
    "maxCustomers": "2400",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "7",
    "storeAddressNameAndNumber": "87 Dundas Street West",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Trenton",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "K8V3P4",
    "storeLatitude": "44.100346",
    "storeLongitude": "-77.576969"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "12-130",
    "retailerCode": "12",
    "retailerName": "Loblaws",
    "regionalCode": "K8V",
    "regionCode": "130",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.22%",
    "topCashback": "2.00%",
    "cashback": "1.46%",
    "maxCustomers": "2900",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "65",
    "storeAddressNameAndNumber": "293 Dundas Street East",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Trenton",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "K8V1M1",
    "storeLatitude": "44.103907",
    "storeLongitude": "-77.553917"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "14-130",
    "retailerCode": "14",
    "retailerName": "Metro",
    "regionalCode": "K8V",
    "regionCode": "130",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.46%",
    "topCashback": "2.00%",
    "cashback": "1.53%",
    "maxCustomers": "2300",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "7",
    "storeAddressNameAndNumber": "53 Quinte Street",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Trenton",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "K8V3S8",
    "storeLatitude": "44.098479",
    "storeLongitude": "-77.576945"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "14-101",
    "retailerCode": "14",
    "retailerName": "Metro",
    "regionalCode": "L1A",
    "regionCode": "101",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.46%",
    "topCashback": "2.00%",
    "cashback": "1.88%",
    "maxCustomers": "700",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "14",
    "storeAddressNameAndNumber": "125 Hope St S",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Port Hope",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L1A4C2",
    "storeLatitude": "43.950765",
    "storeLongitude": "-78.286218"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "1-127",
    "retailerCode": "1",
    "retailerName": "Real Canadian Superstore",
    "regionalCode": "L4J",
    "regionCode": "127",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.05%",
    "topCashback": "1.32%",
    "cashback": "1.10%",
    "maxCustomers": "1000",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "8",
    "storeAddressNameAndNumber": "1054 Centre St",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Thornhill",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L4J3M8",
    "storeLatitude": "43.809864",
    "storeLongitude": "-79.460132"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "3-127",
    "retailerCode": "3",
    "retailerName": "Sobeys",
    "regionalCode": "L4J",
    "regionCode": "127",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.44%",
    "topCashback": "1.85%",
    "cashback": "1.64%",
    "maxCustomers": "1300",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "11",
    "storeAddressNameAndNumber": "9200 Bathurst St",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Richmond Hill",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L4J8W1",
    "storeLatitude": "43.846112",
    "storeLongitude": "-79.460557"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "1-25",
    "retailerCode": "1",
    "retailerName": "Real Canadian Superstore",
    "regionalCode": "L4K",
    "regionCode": "25",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.05%",
    "topCashback": "1.32%",
    "cashback": "1.25%",
    "maxCustomers": "2700",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "7",
    "storeAddressNameAndNumber": "1631 Rutherford Rd",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Vaughan",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L4K0C1",
    "storeLatitude": "43.84163",
    "storeLongitude": "-79.485971"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "5-25",
    "retailerCode": "5",
    "retailerName": "Walmart",
    "regionalCode": "L4K",
    "regionCode": "25",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.29%",
    "topCashback": "1.48%",
    "cashback": "1.37%",
    "maxCustomers": "600",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "14",
    "storeAddressNameAndNumber": "101 Edgeley Blvd",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Concord",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L4K4Z4",
    "storeLatitude": "43.796242",
    "storeLongitude": "-79.530627"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "5-24",
    "retailerCode": "5",
    "retailerName": "Walmart",
    "regionalCode": "L9Y",
    "regionCode": "24",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.29%",
    "topCashback": "1.48%",
    "cashback": "1.41%",
    "maxCustomers": "1500",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "24",
    "storeAddressNameAndNumber": "10 Cambridge",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Collingwood",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L9Y0A1",
    "storeLatitude": "44.499558",
    "storeLongitude": "-80.239329"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "12-24",
    "retailerCode": "12",
    "retailerName": "Loblaws",
    "regionalCode": "L9Y",
    "regionCode": "24",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.22%",
    "topCashback": "2.00%",
    "cashback": "1.70%",
    "maxCustomers": "1300",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "3",
    "storeAddressNameAndNumber": "12 Hurontario St",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Collingwood",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L9Y2L6",
    "storeLatitude": "44.50226",
    "storeLongitude": "-80.218096"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "14-24",
    "retailerCode": "14",
    "retailerName": "Metro",
    "regionalCode": "L9Y",
    "regionCode": "24",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.46%",
    "topCashback": "2.00%",
    "cashback": "1.80%",
    "maxCustomers": "2700",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "20",
    "storeAddressNameAndNumber": "640 First St",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Collingwood",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L9Y4Y7",
    "storeLatitude": "44.5004",
    "storeLongitude": "-80.236942"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "1-133",
    "retailerCode": "1",
    "retailerName": "Real Canadian Superstore",
    "regionalCode": "L9Z",
    "regionCode": "133",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.05%",
    "topCashback": "1.32%",
    "cashback": "1.09%",
    "maxCustomers": "500",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "13",
    "storeAddressNameAndNumber": "25 45th St S",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Wasaga Beach",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L9Z1A7",
    "storeLatitude": "44.473185",
    "storeLongitude": "-80.075389"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "5-133",
    "retailerCode": "5",
    "retailerName": "Walmart",
    "regionalCode": "L9Z",
    "regionCode": "133",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.29%",
    "topCashback": "1.48%",
    "cashback": "1.33%",
    "maxCustomers": "2000",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "23",
    "storeAddressNameAndNumber": "100 Stonebridge Blvd",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Wasaga Beach",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L9Z0C1",
    "storeLatitude": "44.5252",
    "storeLongitude": "-80.003741"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "12-140",
    "retailerCode": "12",
    "retailerName": "Loblaws",
    "regionalCode": "M9N",
    "regionCode": "140",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "1.22%",
    "topCashback": "2.00%",
    "cashback": "1.83%",
    "maxCustomers": "1800",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "63",
    "storeAddressNameAndNumber": "2549 Weston Rd",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Toronto",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "M9N2A7",
    "storeLatitude": "43.708875",
    "storeLongitude": "-79.534199"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "14-911",
    "retailerCode": "14",
    "retailerName": "Metro",
    "regionalCode": "L7G",
    "regionCode": "911",
    "minSpend": "200",
    "maxSpend": "400",
    "baseCashback": "5.60%",
    "topCashback": "6.10%",
    "cashback": "5.60%",
    "maxCustomers": "1200",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "811",
    "storeAddressNameAndNumber": "367 Mountainview Rd S",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Georgetown",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L7G5X3",
    "storeLatitude": "43.631829",
    "storeLongitude": "-79.877996"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "12-911",
    "retailerCode": "12",
    "retailerName": "Real Canadian Super Store",
    "regionalCode": "L7G",
    "regionCode": "911",
    "minSpend": "230",
    "maxSpend": "900",
    "baseCashback": "4.60%",
    "topCashback": "4.90%",
    "cashback": "4.60%",
    "maxCustomers": "1200",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "822",
    "storeAddressNameAndNumber": "171 Guelph St",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Georgetown",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L7G4A1",
    "storeLatitude": "43.65128",
    "storeLongitude": "-79.906542"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "2-911",
    "retailerCode": "2",
    "retailerName": "Food Basics",
    "regionalCode": "L7G",
    "regionCode": "911",
    "minSpend": "190",
    "maxSpend": "1000",
    "baseCashback": "3.70%",
    "topCashback": "4.00%",
    "cashback": "3.70%",
    "maxCustomers": "1200",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "833",
    "storeAddressNameAndNumber": "235 Guelph St",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Georgetown",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L7G4R8",
    "storeLatitude": "43.650418",
    "storeLongitude": "-79.896359"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "21-911",
    "retailerCode": "21",
    "retailerName": "Fresh Co.",
    "regionalCode": "L7G",
    "regionCode": "911",
    "minSpend": "300",
    "maxSpend": "950",
    "baseCashback": "4.90%",
    "topCashback": "5.50%",
    "cashback": "4.90%",
    "maxCustomers": "1200",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "844",
    "storeAddressNameAndNumber": "325 Guelph St",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Georgetown",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L7G4B3",
    "storeLatitude": "43.649703",
    "storeLongitude": "-79.886295"
  },
  {
    "spendRange": "1",
    "retailerRegionCode": "5-911",
    "retailerCode": "5",
    "retailerName": "Walmart",
    "regionalCode": "L7G",
    "regionCode": "911",
    "minSpend": "100",
    "maxSpend": "700",
    "baseCashback": "3.40%",
    "topCashback": "4.10%",
    "cashback": "3.40%",
    "maxCustomers": "1200",
    "startDate": "2021-01-30",
    "endDate": "2021-04-30",
    "storeCode": "855",
    "storeAddressNameAndNumber": "300 Guelph St",
    "storeAddressUnitNumber": "",
    "storeAddressCity": "Georgetown",
    "storeAddressProvince": "ON",
    "storeAddressPostalCode": "L7G4B1",
    "storeLatitude": "43.649149",
    "storeLongitude": "-79.895855"
  }
]

retailerPrograms.forEach(function(obj) {
    db.collection("retailerPrograms").add({
        spendRange: obj.spendRange,
        retailerRegionCode: obj.retailerRegionCode,
        retailerCode: obj.retailerCode,
        retailerName: obj.retailerName,
        regionalCode: obj.regionalCode,
        regionCode: obj.regionCode,
        minSpend: obj.minSpend,
        maxSpend: obj.maxSpend,
        baseCashback: obj.baseCashback,
        topCashback: obj.topCashback,
        cashback: obj.cashback,
        maxCustomers: obj.maxCustomers,
        startDate: obj.startDate,
        endDate: obj.endDate,
        storeCode: obj.storeCode,
        storeAddressNameAndNumber: obj.storeAddressNameAndNumber,
        storeAddressUnitNumber: obj.storeAddressUnitNumber,
        storeAddressCity: obj.storeAddressCity,
        storeAddressProvince: obj.storeAddressProvince,
        storeAddressPostalCode: obj.storeAddressPostalCode,
        storeLatitude: obj.storeLatitude,
        storeLongitude: obj.storeLongitude,

    }).then(function(docRef) {
        console.log("Document written with ID: ", docRef.id);
    })
    .catch(function(error) {
        console.error("Error adding document: ", error);
    });
});